Algoritmo "semnome"
// Disciplina   :Lógica de Programação e Javascript
// Professor   :Obama 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/05/2022
Var
// Seção de Declarações das variáveis 
count:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para count de 15 ate 200 passo 1 faca
     escreval("",count,"²= ",count^2)
fimpara
Fimalgoritmo